### ISSUE TITLE
"dones" incremented before env.step?

### ISSUE THREAD

**Issue by Kostis-S-Z** [Laurans/procgen_adventure#1]
Hello @Laurans !

I am mostly making this issue as an excuse to say thank you for an amazing repo (since the actual issue is a bit insignificant)! It is obvious a lot of work and thought has been put into this and I really appreciate how clean the code and the structure is (which is not always given in such new environments in DL repos)! Everything is very well documented and it was surprisingly easy to understand what is going on, I hope this repo gets the recognition it deserves!

On to the issue. I did notice a minor detail which I am not sure if it is intended or not. In ppo's [sampler](https://github.com/Laurans/procgen_adventure/blob/master/procgen_adventure/algos/ppo/sampler.py#L43) the `storage["dones"] ` is incremented before actually calling `self.env.step(actions)` which might mean that in the end there might be one less `dones` than it should. For example, in deepq's [sampler](https://github.com/Laurans/procgen_adventure/blob/master/procgen_adventure/algos/deepq/sampler.py#L60) you actually increment it after the env.step.

That is all :)

**Comment by Laurans** [comment]
Hi @Kostis-S-Z !

Thank you for your kind message 😄 and thank you for pointing me out the issue.

I fixed it  :)

**Comment by Kostis-S-Z** [comment]
Great! Closing this.
